services:
  app:
    ## O ponto indica que imagem do docker sera construida no diretorio atual
    build: .
    command: /bin/sh -c "npm install && npm start"
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/app
    depends_on:
      - db
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 190991
      MYSQL_DATABASE: conectalento
    ports:
      - "3307:3307"
    volumes:
      - .:/usr/app # Monta o diretório da máquina no container
      - /etc/letsencrypt:/etc/letsencrypt # Monta o volume dos certificados
    working_dir: /usr/app # Define o diretório de trabalho dentro do container

volumes:
  db_data:
